---

- name: Download Datadog PGP key (works with Bionic behind a proxy)
  get_url:
    dest: /usr/local/src/datadog.asc
    mode: 0644
    url: "https://{{ sansible_datadog_apt_keyserver }}/pks/lookup?op=get&search=0x{{ sansible_datadog_apt_key_id }}"

- name: Ensures Datadog PGP key is known
  become: yes
  apt_key:
    file: /usr/local/src/datadog.asc
    id: "{{ sansible_datadog_apt_key_id }}"
    state: present

- name: Add Datadog repo
  become: yes
  apt_repository:
    repo: "{{ sansible_datadog_apt_repo }}"
    state: present
    update_cache: yes

- name: Install Agent
  become: yes
  apt:
    name: datadog-agent
    state: present

- name: Stop and disable datadog
  become: yes
  service:
    name: datadog-agent
    enabled: no
    state: stopped
