---

- name: restart datadog
  become: yes
  service:
    name: datadog-agent
    state: restarted
  when:
    - sansible_datadog_autostart_agent
    - sansible_datadog_enabled

- name: stop datadog
  become: yes
  service:
    name: datadog-agent
    state: stopped
  when:
    - sansible_datadog_autostart_agent
    - sansible_datadog_enabled

- name: start datadog
  become: yes
  service:
    name: datadog-agent
    state: started
  when:
    - sansible_datadog_autostart_agent
    - sansible_datadog_enabled
